### ISSUE TITLE
训练模型报错

### ISSUE THREAD

**Issue by 7xw7** [buppt/ChineseNER#1]
错误代码：
train len: 10721
test len: 3351
valid len 2681
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    calculate(x_test,y_test,epoch)
  File "train.py", line 63, in calculate
    if j<len(y) and id2tag[y[j]][0]=='B':
IndexError: string index out of range

**Comment by buppt** [comment]
我修改了这部分的代码，如果还有问题的话欢迎反馈。
